coreDns:
  enabled: true
  service:
    selector:
      k8s-app: kube-dns
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: true
  service:
    selector:
      k8s-app: ""
      component: etcd
kubeScheduler:
  enabled: false
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeDns:
  enabled: false
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
  jobLabel: node-exporter
  serviceMonitor:
    relabelings:
      - targetLabel: job
        replacement: node-exporter
prometheus-node-exporter:
  podLabels:
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$


prometheus:
  enabled: true
  ## Configuration for Prometheus service
  prometheusSpec:
    scrapeInterval: 30s
    scrapeTimeout: 10s
    enableAdminAPI: true

    externalUrl: ""

    ruleSelectorNilUsesHelmValues: true
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserver: true
    kubeApiserverAvailability: true
    kubeApiserverSlos: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

## Configuration for alertmanager
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    # This inhibt rule is a hack from: https://stackoverflow.com/questions/54806336/how-to-silence-prometheus-alertmanager-using-config-files/54814033#54814033
    inhibit_rules:
      - target_match_re:
           alertname: '.+Overcommit'
        source_match:
           alertname: 'Watchdog'
        equal: ['prometheus']
    receivers:
    - name: 'null'
    - name: 'slack'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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' # <--- AÑADIR EN ESTA LÍNEA EL WEBHOOK CREADO
        send_resolved: true
        channel: '#https://app.slack.com/huddle/T05355S8JKC/C0537L4FZNG' # <--- AÑADIR EN ESTA LÍNEA EL CANAL HUDDLE
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.message }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook_url }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}

## Manages Prometheus and Alertmanager components
prometheusOperator:
  enabled: true

additionalPrometheusRulesMap:
  rule-name:
    groups:
      - name: simpleserver.rules
        rules:
          - alert: HighMemoryUsage
            expr: sum by (pod) (container_memory_usage_bytes{container_name="simpleserver"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{container_name="simpleserver"}) * 100 > 80
            for: 0m
            labels:
              severity: critical
              alertname: "simpleserver container is consuming more memory than requested"
            annotations:
              summary: Pod {{ $labels.pod }} consuming more memory than requested
              description: "Pod consuming more memory than requested"
              message: Pod {{ $labels.pod }} is consuming more memory than requested
              
          - alert: NormalMemoryUsage
            expr: sum by (pod) (container_memory_usage_bytes{container_name="simpleserver"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{container_name="simpleserver"}) * 100 < 80
            for: 5m
            labels:
              severity: warning
              alertname: "simpleserver container is consuming more memory than requested"
            annotations:
              summary: Pod {{ $labels.pod }} consuming more memory than requested
              description: "Pod consuming more memory than requested"
              message: Pod {{ $labels.pod }} is consuming more memory than requested
              
          - alert: HighCpuUsage
            expr: sum by (pod) (rate(container_cpu_usage_seconds_total{container_name="simpleserver"}[1m])) * 100 > 80
            for: 0m
            labels:
              severity: high
              alertname: "simpleserver container is consuming more CPU than requested"
            annotations:
              summary: Pod {{ $labels.pod }} consuming more CPU than requested
              description: "Pod consuming more CPU than requested"
              message: Pod {{ $labels.pod }} is consuming more CPU than requested

          - alert: NormalCpuUsage
            expr: sum by (pod) (rate(container_cpu_usage_seconds_total{container_name="simpleserver"}[1m])) * 100 < 80
            for: 5m
            labels:
              severity: warning
              alertname: "simpleserver container is consuming more CPU than requested"
            annotations:
              summary: Pod {{ $labels.pod }} consuming normal CPU
              description: "Pod consuming normal CPU"
              message: Pod {{ $labels.pod }} is consuming normal CPU
