name: release-build

on:
  push:
    tags:
      - 'v*'
    
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        id: configure-login-dockerhub
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login in to GHCR
        uses: docker/login-action@v2
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            valande/sre-ss:${{ steps.get_version.outputs.version }}
            valande/sre-ss:latest
#            ghcr.io/valande/sre-ss:${{ steps.get_version.outputs.version }}
#            ghcr.io/valande/sre-ss:latest
